/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemasukkanbulanancoba13;

import java.util.ArrayList;

/**
 *
 * @author mn
 */
public class FrameFrom extends javax.swing.JFrame {
    //Masukkan data-data yang dibutuhkan
    int harga, jumlah, total;
    public FrameFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JTextField();
        rb_shopee = new javax.swing.JRadioButton();
        rb_tokopedia = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_hargapk = new javax.swing.JTextField();
        txt_jumlahpk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_hargapc = new javax.swing.JTextField();
        txt_jumlahpc = new javax.swing.JTextField();
        txt_hargapv = new javax.swing.JTextField();
        txt_jumlahpv = new javax.swing.JTextField();
        txt_hargapa = new javax.swing.JTextField();
        txt_jumlahpa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_hargapm = new javax.swing.JTextField();
        txt_jumlahpm = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_totalsemua = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btm_output = new javax.swing.JButton();
        btm_hitung = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        txt_totalpk = new javax.swing.JTextField();
        txt_totalpc = new javax.swing.JTextField();
        txt_totalpv = new javax.swing.JTextField();
        txt_totalpa = new javax.swing.JTextField();
        txt_totalpm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("PEMASUKKAN BULANAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel2.setText("Nama Toko");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 250, -1));

        jLabel3.setText("Tanggal");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel1.add(txt_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 250, -1));

        rb_shopee.setBackground(new java.awt.Color(0, 204, 255));
        rb_shopee.setText("Shopee");
        rb_shopee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_shopeeActionPerformed(evt);
            }
        });
        jPanel1.add(rb_shopee, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        rb_tokopedia.setBackground(new java.awt.Color(0, 204, 255));
        rb_tokopedia.setText("Tokopedia");
        rb_tokopedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_tokopediaActionPerformed(evt);
            }
        });
        jPanel1.add(rb_tokopedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel4.setText("Platfom");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setText("Nama Barang");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setText("Parfum Coklat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel1.add(txt_hargapk, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 80, -1));

        txt_jumlahpk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahpkActionPerformed(evt);
            }
        });
        jPanel1.add(txt_jumlahpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 50, -1));

        jLabel7.setText("Harga");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel8.setText("Jumlah");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel9.setText("Total");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel10.setText("Parfum Kopi");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel11.setText("Parfum Vanila");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel1.add(txt_hargapc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, -1));

        txt_jumlahpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahpcActionPerformed(evt);
            }
        });
        jPanel1.add(txt_jumlahpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 50, -1));
        jPanel1.add(txt_hargapv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 80, -1));

        txt_jumlahpv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahpvActionPerformed(evt);
            }
        });
        jPanel1.add(txt_jumlahpv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 50, -1));
        jPanel1.add(txt_hargapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 80, -1));

        txt_jumlahpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahpaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_jumlahpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 50, -1));

        jLabel12.setText("Parfum Apel");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        jPanel1.add(txt_hargapm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 80, -1));

        txt_jumlahpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahpmActionPerformed(evt);
            }
        });
        jPanel1.add(txt_jumlahpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 50, -1));

        jLabel13.setText("Parfum Mawar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        jPanel1.add(txt_totalsemua, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 350, 190, -1));

        jLabel14.setText("Total");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        btm_output.setText("Output");
        btm_output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_outputActionPerformed(evt);
            }
        });
        jPanel1.add(btm_output, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        btm_hitung.setText("Hitung");
        btm_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_hitungActionPerformed(evt);
            }
        });
        jPanel1.add(btm_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jLabel15.setText("Output");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 470, 280));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, -1, -1));

        txt_totalpk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_totalpkKeyReleased(evt);
            }
        });
        jPanel1.add(txt_totalpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 90, -1));

        txt_totalpc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_totalpcKeyReleased(evt);
            }
        });
        jPanel1.add(txt_totalpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 90, -1));

        txt_totalpv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_totalpvKeyReleased(evt);
            }
        });
        jPanel1.add(txt_totalpv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 90, -1));

        txt_totalpa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_totalpaKeyReleased(evt);
            }
        });
        jPanel1.add(txt_totalpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 90, -1));

        txt_totalpm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_totalpmKeyReleased(evt);
            }
        });
        jPanel1.add(txt_totalpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_jumlahpvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahpvActionPerformed
        // Memasukkan jumlah parfum vanila
        jumlah = Integer.parseInt(txt_jumlahpv.getText());
        txt_jumlahpv.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_txt_jumlahpvActionPerformed

    private void rb_shopeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_shopeeActionPerformed
        //Menentukan harga dengan shopee
        int hargapk = 15500;
        int hargapc = 16400;
        int hargapv = 17300;
        int hargapa = 18200;
        int hargapm = 19100;
        
        if (rb_shopee.isSelected()){
            txt_hargapk.setText(String.valueOf(hargapk));
            txt_hargapc.setText(String.valueOf(hargapc));
            txt_hargapv.setText(String.valueOf(hargapv));
            txt_hargapa.setText(String.valueOf(hargapa));
            txt_hargapm.setText(String.valueOf(hargapm));
        }
    }//GEN-LAST:event_rb_shopeeActionPerformed

    private void rb_tokopediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_tokopediaActionPerformed
        // Menentukan harga dengan tokopedia
        int hargapk = 15100;
        int hargapc = 16200;
        int hargapv = 17300;
        int hargapa = 18400;
        int hargapm = 19500;
        
        if (rb_tokopedia.isSelected()){
            txt_hargapk.setText(String.valueOf(hargapk));
            txt_hargapc.setText(String.valueOf(hargapc));
            txt_hargapv.setText(String.valueOf(hargapv));
            txt_hargapa.setText(String.valueOf(hargapa));
            txt_hargapm.setText(String.valueOf(hargapm));
        }
    }//GEN-LAST:event_rb_tokopediaActionPerformed

    private void txt_jumlahpkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahpkActionPerformed
         // Memasukkan jumlah parfum kopi
        jumlah = Integer.parseInt(txt_jumlahpk.getText());
        txt_jumlahpk.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_txt_jumlahpkActionPerformed

    private void txt_jumlahpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahpcActionPerformed
        // Memasukkan jumlah parfum coklat
        jumlah = Integer.parseInt(txt_jumlahpc.getText());
        txt_jumlahpc.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_txt_jumlahpcActionPerformed

    private void txt_jumlahpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahpaActionPerformed
        // Memasukkan jumlah parfum apel
        jumlah = Integer.parseInt(txt_jumlahpa.getText());
        txt_jumlahpa.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_txt_jumlahpaActionPerformed

    private void txt_jumlahpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahpmActionPerformed
        // Memasukkan jumlah parfum mawar
        jumlah = Integer.parseInt(txt_jumlahpm.getText());
        txt_jumlahpm.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_txt_jumlahpmActionPerformed

    private void btm_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_hitungActionPerformed
        // Menghitung total:
        txt_totalsemua.setText(String.valueOf(cetak()));
    }//GEN-LAST:event_btm_hitungActionPerformed

    private void btm_outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_outputActionPerformed
        // output :
        txt_area.setText(
                "Nama Toko      : "+txt_nama.getText()+"\n"
                + "Tanggal      : "+txt_tanggal.getText()+"\n"
                + "============================================="+"\n"
                + "|            Nama Barang             |       Harga      |        Jumlah      |       Total         |"+"\n"
                + "|    Parfum Kopi     "+"\t"+txt_hargapk.getText()+"\t"+txt_jumlahpk.getText()+"\t"+txt_totalpk.getText()+"|"+"\n"
                + "|    Parfum Coklat   "+"\t"+txt_hargapc.getText()+"\t"+txt_jumlahpc.getText()+"\t"+txt_totalpc.getText()+"|"+"\n"
                + "|    Parfum Vanila   "+"\t"+txt_hargapv.getText()+"\t"+txt_jumlahpv.getText()+"\t"+txt_totalpv.getText()+"|"+"\n"
                + "|    Parfum Apel     "+"\t"+txt_hargapa.getText()+"\t"+txt_jumlahpa.getText()+"\t"+txt_totalpa.getText()+"|"+"\n"
                + "|    Parfum Mawar    "+"\t"+txt_hargapm.getText()+"\t"+txt_jumlahpm.getText()+"\t"+txt_totalpm.getText()+"|"+"\n"
                + "Total Pemasukkan : "+txt_totalsemua.getText());
    }//GEN-LAST:event_btm_outputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Untuk menghapus semua data
         txt_nama.setText("");
        txt_tanggal.setText("");
        txt_jumlahpk.setText("");
        txt_jumlahpc.setText("");
        txt_jumlahpv.setText("");
        txt_jumlahpa.setText("");
        txt_jumlahpm.setText("");
        txt_hargapk.setText("");
        txt_hargapc.setText("");
        txt_hargapa.setText("");
        txt_hargapv.setText("");
        txt_hargapa.setText("");
        txt_hargapm.setText("");
        txt_area.setText("");
        txt_totalpk.setText("");
        txt_totalpc.setText("");
        txt_totalpv.setText("");
        txt_totalpa.setText("");
        txt_totalpm.setText("");
        txt_totalsemua.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_totalpkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalpkKeyReleased
         // Menghitung total parfum kopi
        int a, b, c;
        a = Integer.valueOf(txt_hargapk.getText());
        b = Integer.valueOf(txt_jumlahpk.getText());
        c = a*b;
        txt_totalpk.setText(""+c);
    }//GEN-LAST:event_txt_totalpkKeyReleased

    private void txt_totalpcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalpcKeyReleased
         // Menghitung total parfum coklat
        int a, b, c;
        a = Integer.valueOf(txt_hargapc.getText());
        b = Integer.valueOf(txt_jumlahpc.getText());
        c = a*b;
        txt_totalpc.setText(""+c);
    }//GEN-LAST:event_txt_totalpcKeyReleased

    private void txt_totalpvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalpvKeyReleased
        // Menghitung total parfum vanila
        int a, b, c;
        a = Integer.valueOf(txt_hargapv.getText());
        b = Integer.valueOf(txt_jumlahpv.getText());
        c = a*b;
        txt_totalpv.setText(""+c);
    }//GEN-LAST:event_txt_totalpvKeyReleased

    private void txt_totalpaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalpaKeyReleased
        // Menghitung total parfum apel
        int a, b, c;
        a = Integer.valueOf(txt_hargapa.getText());
        b = Integer.valueOf(txt_jumlahpa.getText());
        c = a*b;
        txt_totalpa.setText(""+c);
    }//GEN-LAST:event_txt_totalpaKeyReleased

    private void txt_totalpmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalpmKeyReleased
        // Menghitung total parfum mawar
        int a, b, c;
        a = Integer.valueOf(txt_hargapm.getText());
        b = Integer.valueOf(txt_jumlahpm.getText());
        c = a*b;
        txt_totalpm.setText(""+c);
    }//GEN-LAST:event_txt_totalpmKeyReleased

    int cetak(){  
         // import the ArrayList class
         ArrayList<Integer> totalsemua = new ArrayList<Integer>();
         totalsemua.add(Integer.valueOf(txt_totalpk.getText()));
         totalsemua.add(Integer.valueOf(txt_totalpc.getText()));
         totalsemua.add(Integer.valueOf(txt_totalpv.getText()));
         totalsemua.add(Integer.valueOf(txt_totalpa.getText()));
         totalsemua.add(Integer.valueOf(txt_totalpm.getText()));
         
         int total = 0;
         for(int i = 0 ; i < totalsemua.size();i++){
             total += totalsemua.get(i);
         }
         return total;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_hitung;
    private javax.swing.JButton btm_output;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_shopee;
    private javax.swing.JRadioButton rb_tokopedia;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_hargapa;
    private javax.swing.JTextField txt_hargapc;
    private javax.swing.JTextField txt_hargapk;
    private javax.swing.JTextField txt_hargapm;
    private javax.swing.JTextField txt_hargapv;
    private javax.swing.JTextField txt_jumlahpa;
    private javax.swing.JTextField txt_jumlahpc;
    private javax.swing.JTextField txt_jumlahpk;
    private javax.swing.JTextField txt_jumlahpm;
    private javax.swing.JTextField txt_jumlahpv;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tanggal;
    private javax.swing.JTextField txt_totalpa;
    private javax.swing.JTextField txt_totalpc;
    private javax.swing.JTextField txt_totalpk;
    private javax.swing.JTextField txt_totalpm;
    private javax.swing.JTextField txt_totalpv;
    private javax.swing.JTextField txt_totalsemua;
    // End of variables declaration//GEN-END:variables
}
